services:
  # Redis Service - Optimized for Docker networking
  redis:
    image: redis:7-alpine
    container_name: bondhu-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --maxmemory 32mb --maxmemory-policy allkeys-lru --save "" --appendonly no --tcp-keepalive 60 --timeout 300
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 6h
      timeout: 60s
      retries: 1
      start_period: 60s
    networks:
      - bondhu-network
    deploy:
      resources:
        limits:
          memory: 48M
          cpus: '0.1'
    security_opt:
      - no-new-privileges:true

  # Main Application Service
  bondhu-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bondhu-api
    ports:
      - "8000:8000"
    environment:
      # Redis configuration - use Docker service name
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ENABLE_REDIS=true
      
      # Application settings
      - PYTHONPATH=/app
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - ENABLE_RL=${ENABLE_RL:-true}
      - ENABLE_SCHEDULER=${ENABLE_SCHEDULER:-true}
      - WORKERS=${WORKERS:-2}
      - MAX_CONCURRENCY=${MAX_CONCURRENCY:-50}
    env_file:
      - .env
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - bondhu-network
    healthcheck:
      test: [ "CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=10)" ]
      interval: 12h
      timeout: 60s
      retries: 1
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
    security_opt:
      - no-new-privileges:true

  # Celery Worker - Minimal resource usage
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bondhu-celery-worker
    # Use solo pool for Windows/WSL compatibility (prevents SIGKILL)
    command: celery -A core.celery_app worker --loglevel=info --pool=solo --concurrency=1
    environment:
      # Redis configuration - use Docker service name
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      
      # Celery-specific settings for Windows/WSL
      - FORKED_BY_MULTIPROCESSING=1
      - C_FORCE_ROOT=true
      
      # Application settings
      - PYTHONPATH=/app
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - CELERY_WORKER=true
    env_file:
      - .env
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
      bondhu-api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - bondhu-network
    deploy:
      resources:
        limits:
          memory: 80M
          cpus: '0.1'
    security_opt:
      - no-new-privileges:true

  # Frontend Service - Next.js Application
  # bondhu-frontend:
  #   build:
  #     context: ../bondhu-landing
  #     dockerfile: Dockerfile.dev
  #   container_name: bondhu-frontend
  #   ports:
  #     - "127.0.0.1:3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #     - NEXT_TELEMETRY_DISABLED=1
  #     - NEXT_PUBLIC_API_URL=http://localhost:8000
  #     - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3000
  #   env_file:
  #     - ../bondhu-ai/.env
  #   depends_on:
  #     - bondhu-api
  #   restart: unless-stopped
  #   networks:
  #     - bondhu-network
  #   volumes:
  #     - ../bondhu-landing:/app
  #     - /app/node_modules
  #     - /app/.next
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 256M
  #         cpus: '0.3'
  #   security_opt:
  #     - no-new-privileges:true

volumes:
  redis-data:
    driver: local

networks:
  bondhu-network:
    driver: bridge
