collect_data_task:
  description: >
    Gather the latest multimodal signals for the current user session,
    including music listening, video watch history, gameplay telemetry,
    and survey/free-form feedback. Normalize everything into a single JSON snapshot.
  expected_output: >
    {
      "music": [...],
      "video": [...],
      "gaming": [...],
      "survey": [...],
      "ingest_timestamp": "ISO-8601"
    }
  agent: data_collection_agent

analyze_personality_task:
  description: >
    Merge the freshly collected signals with historical docs to update
    the user’s Big Five traits, motivations, and risk markers.
    Detect drift or conflicts against the existing persona embedding.
  expected_output: >
    {
      "persona_embedding_id": "...",
      "traits": {...},
      "drift_alert": bool,
      "notes": [...]
    }
  agent: personality_analysis_agent

generate_interaction_task:
  description: >
    Prepare the conversational plan: summarise salient chat points,
    craft empathetic replies aligned with the digital twin, and surface
    clarification questions if context is missing or safety flags arose.
  expected_output: >
    {
      "response_text": "...",
      "follow_up_questions": [...],
      "safety_notes": [...]
    }
  agent: interaction_agent

synthesize_recommendations_task:
  description: >
    Produce ranked bundles of music cards and video suggestions tailored
    to current mood and long-term preferences, including rationales,
    confidence scores, and feedback hooks for reinforcement learning.
  expected_output: >
    {
      "music_cards": [...],
      "video_cards": [...],
      "rationales": [...],
      "feedback_prompts": [...]
    }
  agent: recommendation_agent

orchestrate_workflow_task:
  description: >
    Coordinate the full workflow: trigger data collection, wait for analysis,
    reconcile outputs, and package the final payload for downstream UIs
    while logging memory updates and safety decisions.
  expected_output: >
    {
      "conversation_plan": {...},
      "recommendations": {...},
      "memory_updates": [...],
      "alerts": [...]
    }
  agent: orchestrator_agent
  depends_on:
    - collect_data_task
    - analyze_personality_task
    - generate_interaction_task
    - synthesize_recommendations_task